function three_by_three_non_existence()
    % visualization of the non existence proof for larger structues
    k = 0;
    h = 2^(-k);
    N = 2^(k+1);
    L = N^2;
    t11 = [-0.87; 0.87; 1/2];
    a = 0.45;
    b = omega(a, 1, 0);
    %a = 36.9811 / 360 * (2 * pi)
    %b = 31.3686 / 360 * (2 * pi)
    c = omega(b, 1, 0);
    d = omega(c, 1, 0);
    e = omega(d, 1, 0);


    U0 = init_configuration(k);

    p1 = U0(1:3);
    Q1 = reshape(U0(4:12), 3, 3);

    [p2, Q2] = calculate_neighbor(h, t11, 3, "n", p1, Q1, a);
    [p3, Q3] = calculate_neighbor(h, t11, 3, "e", p1, Q1, b);
    [p4, Q4] = calculate_neighbor(h, t11, 3, "w", p1, Q1, d);
    [p5, Q5] = calculate_neighbor(h, t11, 3, "s", p1, Q1, c);

    [p6, Q6] = calculate_neighbor(h, t11, 4, "e", p2, Q2, -b);
    [p7, Q7] = calculate_neighbor(h, t11, 4, "s", p3, Q3, -c);
    [p8, Q8] = calculate_neighbor(h, t11, 4, "w", p5, Q5, -d);
    [p9, Q9] = calculate_neighbor(h, t11, 4, "n", p4, Q4, -a);

    U = vertcat(p1, ...
                reshape(Q1, [], 1), ...
                ...
                p2, ...
                reshape(Q2, [], 1), ...
                ...
                p3, ...
                reshape(Q3, [], 1), ...
                ...
                p4, ...
                reshape(Q4, [], 1), ...
                ...
                p5, ...
                reshape(Q5, [], 1), ...
                ...
                p6, ...
                reshape(Q6, [], 1), ...
                ...
                p7, ...
                reshape(Q7, [], 1), ...
                ...
                p8, ...
                reshape(Q8, [], 1), ...
                ...
                p9, ...
                reshape(Q9, [], 1));

    plot_skeleton_by_list(U, h, [2, 3, 3, 3, 3, 4, 4, 4, 4], t11, 1, 0);
end